# Generated by Django 3.2.9 on 2022-01-01 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('before', 'Przed naprawą'), ('in_progress', 'W trakcie naprawy'), ('after', 'Po naprawie')], default='before', max_length=15),
        ),
    ]
